Feature/add er diagram
tokaisagami/nightmare-app pull request #3
Opened 2024-09-26 12:18 UTC by tokaisagami

![er-diagram_01](https://github.com/user-attachments/assets/0bd87248-b311-4446-bb81-bbb9818a91c7)

2024-09-26 12:38 UTC, tokaisagami commented
### 追記事項
各テーブルの項目の説明

1. Usersテーブル
id: ユーザーの識別子（主キー）
username: ユーザー名
email: メールアドレス
password_digest: パスワードのハッシュ
created_at: 登録日時
updated_at: 更新日時

2. Nightmaresテーブル
id: 悪夢の識別子（主キー）
user_id: ユーザーID（外部キー、Usersテーブルへの参照）
description: 悪夢の内容
modified_description: 改変後の悪夢の内容
ending_type: 選択した結末の種類
published: 公開ステータス（ブール値）
created_at: 作成日時
updated_at: 更新日時

2024-09-27 04:10 UTC, tmtkzk0823 commented
ご提出ありがとうございます。
以下、コメントになります。

---

- テーブル名_カラム名になっているカラムは、テーブル名を除いた表記にするといいかと思います
```
例：
  - usersテーブル
  　  user_name → name
```


- `ending_type:`というカラムを持っていますが、`type`という命名は`STI`という技術を使用する際によく使われる命名なので、STIを使用しない場合、違う命名に変更することを検討してください。

2024-09-27 13:00 UTC, tokaisagami commented
プルリクご確認ありがとうございます。
以下、指摘対応内容と対応後のER図スクリーンショットです。

- テーブル名_カラム名になっているカラムは、テーブル名を除いた表記にするといいかと思います
  ⇒Usersテーブルの項目usernameをnameに修正しました。

- ending_type:というカラムを持っていますが、typeという命名はSTIという技術を使用する際によく使われる命名なので、STIを使用しない場合、違う命名に変更することを検討してください。
  ⇒STIは現在使用予定でないため、ending_typeをending_categoryに修正しました。


![er-diagram_02](https://github.com/user-attachments/assets/4848f027-dc3e-4d02-b8dd-c80a6ffa7e90)

2024-09-29 06:22 UTC, tarakish requested changes
修正確認しました。以下追加のコメントです！

---

- Users
  - 認証機能はなにかgemを使う想定でしょうか？そうであれば必要なカラムが足りているか一度ご確認をお願いします。

2024-10-03 01:53 UTC, Tsuchiya2 commented
概ね良いかと思います。LGTMです。
修正が必要になった際は適宜修正して開発を進めましょう。

2024-10-03 14:13 UTC, merged